name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: |
          uv pip install --system --requirement requirements.txt

      - name: Test
        run: |
          pytest
